version: "3"
services:
  caruna-importer:
    depends_on:
      - influxdb
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=influxdb
      - DB_PORT=8086
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  influxdb-storage:
  grafana-storage:

